---
- name: Import the Elastic Key (Ubuntu)
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Import Elastic Key (CentOS)
  become: true
  rpm_key:
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: ansible_distribution == "CentOS"

- name: install and add elastic apt repo (Ubuntu)
  lineinfile:
    path: /etc/apt/sources.list.d/elastic.list
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
  when: ansible_distribution == "Ubuntu"

- name: install and add elastic rpm repo (CentOS)
  lineinfile:
    path: /etc/yum.repos.d/elastic.repo
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "baseurl=https://artifacts.elastic.co/packages/8.x/yum"
  when: ansible_distribution == "CentOS"

- name: install and add curator apt repo (Ubuntu)
  lineinfile:
    path: /etc/apt/sources.list.d/elastic.list
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "deb [arch=amd64] https://packages.elastic.co/curator/5/debian stable main"
  when: ansible_distribution == "Ubuntu"

- name: install and add curator rpm repo
  lineinfile:
    path: /etc/yum.repos.d/elastic.rpo
    state: present
    create: true
    backup: true
    mode: 0644
    owner: root
    group: root
    line: "baseurl=https://packages.elastic.co/curator/5/centos/7"
  when: ansible_distribution == "CentOS"

- name: install elasticsearch (Ubuntu)
  apt:
    name:
      - elasticsearch
      - elasticsearch-curator
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install elasticsearch (CentOS)
  become: true
  yum:
    name:
      - elasticsearch
    enablerepo: elasticsearch
    state: present
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Configuring cluster.name
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#cluster.name: my-application'
    replace: 'cluster.name: Villareal_cluster'

- name: Configuring node.name
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#node.name: node-1'
    replace: 'node.name: node-1'

- name: Configuring http.port
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '#http.port: 9200'
    replace: 'http.port: 9200'

- name: Configuring network.host
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'xpack.security.enabled: true'
    replace: 'xpack.security.enabled: false'

- name: Enabling ElasticSearch Service
  service:
    name: elasticsearch
    enabled: yes

- name: Modifying service file
  replace:
    path: /usr/lib/systemd/system/elasticsearch.service
    regexp: "TimeoutStartSec=75"
    replace: "TimeoutStartSec=300"

- name: Opening port for elastic search (CentOS)
  become: true
  shell: |
    firewall-cmd  --permanent --zone=public -add-port=9200/tcp
    sleep 10
    firewall-cmd --reload
  when: ansible_distribution == "CentOS"

- name: Opening port for elastic search (Ubuntu)
  become: true
  ufw:
    rule: allow
    port: "9200"
    comment: "Allow Elasticsearch"
  when: ansible_distribution == "Ubuntu"

- name: Enabling elasticseach service
  shell: |
    systemctl enable elasticsearch.service
    sleep 10
    systemctl start elasticsearch.service
